// <auto-generated />
namespace CRUD_CF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class pkfk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pkfk));
        
        string IMigrationMetadata.Id
        {
            get { return "202009030333339_pkfk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
